FIRSTSET = {
    "program": ["def", "int", "double", "if", "while", "print", "return", "identifier"] ,
    "fdecls": ["def", "EPSILON"] ,
    "fdeclsEnd": ["def", "EPSILON"] ,
    "fdec": ["def"],
    "fdecEnd": ["def", "EPSILON"],
    "params": ["int", "double", "EPSILON"],
    "paramsEnd": [",", "EPSILON"],
    "fname": ["identifier"],
    "declarations": ["int", "double", "EPSILON"],
    "declarationsEnd": ["int", "double", "EPSILON"],
    "decl": ["int", "double"],
    "declEnd": ["int", "double", "EPSILON"],
    "type": ["int", "double"],
    "varlist": ["identifier"],
    "varlistEnd": [",", "EPSILON"],
    "statementSeq": ["if", "while", "print", "return", "identifier", "EPSILON"],
    "statementSeqEnd": [";", "EPSILON"],
    "statement": ["if", "while", "print", "return", "identifier", "EPSILON"],
    "else": ["else", "EPSILON"],
    "expr": ["identifier", "double", "int", "doubleE", "("],
    "exprEnd": ["+", "-", "EPSILON"],
    "term": ["identifier", "double", "int", "doubleE", "("],
    "termEnd": ["*", "/", "%", "EPSILON"],
    "factor": ["identifier", "int", "double", "doubleE", "("],
    "exprSeq": ["identifier", "double", "int", "doubleE", "("],
    "exprSeqEnd": [",", "EPSILON"],
    "bexpr": ["not", "("],
    "bexprEnd": ["or", "EPSILON"],
    "bterm": ["not", "("],
    "btermEnd": ["and", "EPSILON"],
    "bfactor": ["not", "("],
    "bfactorEnd": ["EPSILON"],
    "comp": ["<", ">", "==", "<=", ">=", "<>"],
    "var": ["identifier"],
    "varEnd": ["[", "EPSILON"],
}